In [2]:
import pandas as pd

## DATAFRAME

In [3]:
df_BANK_marketing = pd.read_csv("S4_df_BANK_marketing.csv")
df_BANK_marketing

,id,age,job,marital,education,is_in_default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit,balance_normalizado,estado_balance
0,1,59.0,admin.,married,secondary,0,2343,1,0,unknown,5,may,1042,1,-1,0,unknown,1,0.260495,Saldo Alto
1,2,59.0,admin.,married,secondary,0,2343,1,0,unknown,5,may,1042,1,-1,0,unknown,1,0.260495,Saldo Alto
2,3,56.0,admin.,married,secondary,0,45,0,0,unknown,5,may,1467,1,-1,0,unknown,1,-0.455442,Saldo Bajo
3,4,41.0,technician,married,secondary,0,1270,1,0,unknown,5,may,1389,1,-1,0,unknown,1,-0.073796,Saldo Medio Alto
4,5,55.0,services,married,secondary,0,2476,1,0,unknown,5,may,579,1,-1,0,unknown,1,0.301931,Saldo Alto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39183,45763,41.0,management,divorced,tertiary,0,107,1,0,cellular,17,jul,122,17,-1,0,unknown,0,-0.436126,Saldo Bajo
39184,45764,57.0,management,married,tertiary,0,350,0,0,telephone,4,may,87,3,-1,0,unknown,0,-0.360420,Saldo Medio
39185,45765,84.0,retired,married,secondary,0,81204,0,0,telephone,28,dec,679,1,313,2,other,1,24.829468,Saldo Muy Alto
39186,45766,29.0,blue-collar,married,primary,0,544,0,1,cellular,21,jul,121,4,-1,0,unknown,0,-0.299980,Saldo Medio
39187,45767,34.0,technician,married,secondary,0,0,1,0,cellular,5,aug,231,2,2,3,success,1,-0.469462,Saldo Bajo

## 1) ConversiÃ³n DepÃ³sito

In [4]:
clientes_contactados = len(df_BANK_marketing)
clientes_suscritos = df_BANK_marketing['deposit'].sum()
porcentaje_conversion = (clientes_suscritos / clientes_contactados) * 100
print(f'Porcentaje de ConversiÃ³n a DepÃ³sito: {porcentaje_conversion.round(2)}%')

Porcentaje de ConversiÃ³n a DepÃ³sito: 47.12%

## 2) Promedio de la duraciÃ³n de las llamadas de los suscriptores

In [5]:
# Filtrado de los suscriptores
suscriptores = df_BANK_marketing[df_BANK_marketing['deposit'] == 1]


promedio_duracion_llamadas = suscriptores['duration'].mean()
print(f'Promedio de DuraciÃ³n de Llamadas de Suscriptores: {promedio_duracion_llamadas.round(2)} segundos')

Promedio de DuraciÃ³n de Llamadas de Suscriptores: 537.4 segundos

## 3) Porcentaje de llamadas a telÃ©fono fijo o a mÃ³vil

In [6]:
llamadas_telefono_movil = df_BANK_marketing[df_BANK_marketing['contact'].isin(['telephone', 'cellular'])].shape[0]
total_llamadas = df_BANK_marketing.shape[0]
porcentaje_llamadas = (llamadas_telefono_movil / total_llamadas) * 100
print(f'Porcentaje de Llamadas a TelÃ©fono o MÃ³vil: {porcentaje_llamadas:.2f}%')

Porcentaje de Llamadas a TelÃ©fono o MÃ³vil: 79.00%

## 4) Promedio de contactos previos de suscriptores

In [7]:
num_suscriptores = suscriptores.shape[0] #usamos suscriptores del segundo KPI
suma_contactos_previos = suscriptores['previous'].sum()
promedio_contactos_previos = suma_contactos_previos / num_suscriptores
print(f'Promedio de Contactos Previos de Suscriptores: {promedio_contactos_previos.round(2)}')

Promedio de Contactos Previos de Suscriptores: 1.18

## 5) Mes con mayor tasa de conversiÃ³n

In [8]:
# Agrupar por mes y calcular el porcentaje de conversiÃ³n por mes
conversion_por_mes = df_BANK_marketing.groupby('month')['deposit'].mean() * 100
mes_mayor_conversion = conversion_por_mes.idxmax()
mayor_porcentaje_conversion = conversion_por_mes.max()
print(f'Mes con Mayor Tasa de ConversiÃ³n: {mes_mayor_conversion} ({mayor_porcentaje_conversion.round(2)}%)')

Mes con Mayor Tasa de ConversiÃ³n: dec (90.3%)